# Generated by Django 4.0.3 on 2022-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('stattut', models.CharField(max_length=20)),
            ],
        ),
    ]
