# Generated by Django 4.0.3 on 2022-03-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='stattut',
            new_name='statut',
        ),
    ]
